### ISSUE TITLE
Minecraft bug

### ISSUE THREAD

**Issue by ProtoMan8WasTaken** [Atlas-OS/Atlas#35]
The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: Pixel format not accelerated
Exit Code: -1

I have restarted, tried updating graphics and stuff
heres the crash report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/10/21 5:42 AM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at tech.cy.al(Unknown Source)
	at tech.cy.aj(Unknown Source)
	at tech.cy.l(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at me.paolo.CrackMain.main(deEtBVGn)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at tech.cy.al(Unknown Source)
	at tech.cy.aj(Unknown Source)

-- Initialization --
Details:
Stacktrace:
	at tech.cy.l(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at me.paolo.CrackMain.main(deEtBVGn)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 456300360 bytes (435 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Dortware
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	OptiFine Version: OptiFine_1.8_HD_U_H6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 4
BTW THE GRAPHICS CARD IS MICROSOFT BASIC DISPLAY ADAPTER

**Comment by Zusier** [comment]
Install gpu drivers

**Comment by ProtoMan8WasTaken** [comment]
k

**Comment by ProtoMan8WasTaken** [comment]
> Install gpu drivers

what do u reccomend? i tryed GeForce but they wont work

**Comment by Zusier** [comment]
Use NVCleanstall in the Atlas >> Drivers folder

**Comment by ProtoMan8WasTaken** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/85041531/125136884-ca223100-e14a-11eb-9ca4-a3cd8057099d.png)
what now

**Comment by Zusier** [comment]
What gpu do you have?

**Comment by ProtoMan8WasTaken** [comment]
intel(r) UHC Graphics 610

**Comment by ProtoMan8WasTaken** [comment]
i just got it from drivereasy

**Comment by ProtoMan8WasTaken** [comment]
hold up, minecraft works now thanks!
